config/routes.rb
Notable::Application.routes.draw do
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users
  resources :sessions
  resources :topics

  root to: "topics#index"
  # root to: "topics#index"
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body

  validates :body, :presence => true

  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :title

  validates :title, :presence => true

  has_many :notes, :dependent => :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email

  has_many :topics, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged In Succesfully!"
    else
      flash.now.alert = "Woops! Email or password invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "See you soon!"
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.includes(:notes).find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_login.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %> |
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> |
  <%= link_to "Log In", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notable</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="main">
      <div id="brand">
        <%= link_to "Notable", root_url %>
      </div>
      <div id="login_header">
        <%= render "layouts/login" %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for [@topic, @note = Note.new] do |f| %>
  <% if @note.errors.any? %>
    <div id="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/notes/_note.html.erb
<div class="note">
  <%= note.body %>
</div>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
  <div class="topics">
    <ul>
      <li><%= link_to topic.title, topic_path(topic) %></li>
    </ul>
  </div>
<% end %>

app/views/topics/show.html.erb
<h2><%= @topic.title %></h2>

<div class="notes">
  <h3>Notes</h3>
  <div class="new_note">
    <%= render "notes/form" %>
  </div>
  <div class="note_list">
    <%= render @topic.notes %>
  </div>
</div>

app/views/users/new.html.erb
<div class="authentication_form">
  <h1>Sign Up</h1>

  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Sign Up" %></div>
  <% end %>
</div>